# disable PostgreSQL dev service run with project start
quarkus.http.host-enabled=true
quarkus.http.port=9090
quarkus.devservices.enabled=false

# Logging
quarkus.log.level=info
quarkus.log.syslog.enable=true

# DB
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=local
quarkus.datasource.password=local
#quarkus.datasource.reactive.url=postgresql://localhost:5432/hash-arts
#quarkus.datasource.reactive.max-size=20
quarkus.datasource.jdbc=true
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/hash-arts
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# Migration
quarkus.flyway.active=true
quarkus.flyway.migrate-at-start=true
#quarkus.flyway.clean-at-start=true

# Client
#nft.model.google.key=
quarkus.rest-client.google-api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp-image-generation:generateContent

# Nft
nft.token.mint.gateway.prefix=https://dweb.link/ipfs/
nft.token.mint.gateway.local.prefix=http://localhost:8080/ipfs/