services:

  postgres:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: hash-arts
    ports:
      - "5432:5432"
    volumes:
      - hash-art-postgresql-data:/var/lib/postgresql/data
    networks:
      - hash-art-net
    command: postgres -c listen_addresses=*

  ipfs:
    image: 'ipfs/kubo:v0.34.1'
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5001:5001"
    user: "ipfs"
    volumes:
      - hash-art-ipfs-export:/export
      - hash-art-ipfs-data:/data/ipfs
    networks:
      - hash-art-net
    command: [ "daemon", "--enable-pubsub-experiment" ]

volumes:
  hash-art-postgresql-data:
  hash-art-ipfs-export:
  hash-art-ipfs-data:

networks:
  hash-art-net: